M48
; DRILL file {KiCad (6.0.9)} date lun. 12 déc. 2022 15:39:45
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-12T15:39:45+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.3039Y-1.6004
X1.3039Y-4.9764
X10.0835Y-1.6004
X10.0835Y-4.9764
T0
M30
